version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./deployment/configs/nginx.conf:/etc/nginx/nginx.conf
      - ./deployment/configs/variable.conf:/etc/nginx/variable.conf
  app:
    container_name: busan-beach-app
    image: busan-beach:0.0.2
    build:
      context: .
      args:
        NEXT_PUBLIC_ENV: production
